# Generated by Django 5.0.3 on 2024-03-15 23:01

import onboarding.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_user_created_at'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', onboarding.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
